---

- name: Configure NFS mounts
  become: yes
  action:
    module: mount
    boot: "{{ item.boot | default(omit) }}"
    dump: "{{ item.dump | default(omit) }}"
    fstab: "{{ item.fstab | default(omit) }}"
    fstype: "{{ item.fstype | default(nfs_default_fstype) }}"
    opts: "{{ item.opts | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    state: "{{ item.state }}"
  with_items: "{{ nfs_mounts | default([]) }}"
